# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dd2cade9afd34843a98a698abb77c7d21b798bea89efc79602268c482fb6c692ed7d75bb5f04484ff5df3a51ee622ae9242db096d5deb727c2da9b0415cd1e6

test:
  secret_key_base: 584f2be6e4ba541050df9bb4a5a05bdd90a4c37581ebd112ce66e90dbc3281f5d056724c5235aabee6d59f5b8027eede1c3b1c64f9655ed658bc113ac67652eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
